server:
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/full_stack_customer
    username: postgres
    password: Admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  flyway:
    baseline-on-migrate: true
  main:
    web-application-type: servlet
